### PR TITLE
feat: added fx fields in quote request and response payloads

### PR DESCRIPTION
**Pull request by ZweHMyat**

### CODE REVIEW

**Review by myo-min-htet — APPROVED** [review]
Looks good to me.

**Comment by bushjames** [comment]
@ZweHMyat please could you add a link here to the API specification document that has these definitions for reference. OpenAPI/swagger if available please. Many thanks.

**Comment by bushjames** [comment]
my apologies @ZweHMyat I think this is the document: https://github.com/mojaloop/mojaloop-specification/blob/master/fspiop-api/documents/v2.0-document-set/fspiop-v2.0-openapi3-implementation-draft.yaml

**Comment by ZweHMyat** [comment]
> my apologies @ZweHMyat I think this is the document: https://github.com/mojaloop/mojaloop-specification/blob/master/fspiop-api/documents/v2.0-document-set/fspiop-v2.0-openapi3-implementation-draft.yaml

No problem James. Yes that is the doc I have been referencing for FX developments.

**Pull request merged**
